INSERT INTO todo(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10001, 'joona', 'Get Spring', CURRENT_DATE(), false);

INSERT INTO todo(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10002, 'joona', 'Get Node.js', CURRENT_DATE(), false);

INSERT INTO todo(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10003, 'joona', 'Get React', CURRENT_DATE(), false);

INSERT INTO todo(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10004, 'joona', 'Get Java', CURRENT_DATE(), false);

INSERT INTO todo(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10005, 'joona', 'Get Python', CURRENT_DATE(), false);